/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SqliteBridge */

#ifndef _Included_SqliteBridge
#define _Included_SqliteBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SqliteBridge
 * Method:    execSql
 * Signature: (Ljava/lang/String;Ljava/lang/String;LDbData;)V
 */
JNIEXPORT void JNICALL Java_SqliteBridge_execSql
  (JNIEnv *, jobject, jstring, jstring, jobject);

JNIEXPORT void JNICALL Java_SqliteBridge_execSqlDML
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     bridge_SqliteBridge
 * Method:    createDatabase
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bridge_SqliteBridge_createDatabase
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
