/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyNewString */

#ifndef _Included_MyNewString
#define _Included_MyNewString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyNewString
 * Method:    getString
 * Signature: ([CI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MyNewString_getString
  (JNIEnv *, jclass, jcharArray, jint);

#ifdef __cplusplus
}
#endif
#endif
